
export const COUNTER_ADD = 'COUNTER_ADD'
export const COUNTER2_ADD = 'COUNTER2_ADD'
export const COUNTER_SUB = 'COUNTER_SUB'
export const COUNTER_RESET = 'COUNTER_RESET'
export const COUNTER_RANDOM = 'COUNTER_RANDOM'
export const AUTHORIZATION = 'AUTHORIZATION'